/*
University of Greenwich
School of Computing & Mathematical Sciences
Final Year Project
Author: Chinedu Gabriel Asinugo.
Student ID: 000433816
Class of 2013
* 
* Bits and parts of this class was obtained from various (http://code.google.com/), Sourceforge and guthub Projects,
 */

package finalproject;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.JFrame;

/**
 *
 * @author  Chinedu Gabriel Asinugo
 */
public class DesktopViewer extends javax.swing.JFrame {
    Rectangle rect;
    public LDClient lcl;
    /** Creates new form DesktopViewer */
    public DesktopViewer(JFrame fr) {
        //super(fr, false);
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Viewing Desktop Of ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    lblDisplay.setBounds(0, 0, evt.getComponent().getWidth(), evt.getComponent().getHeight());
    this.setVisible(true);
    
}//GEN-LAST:event_formWindowOpened

private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
    lblDisplay.setBounds(0, 0, evt.getComponent().getWidth(), evt.getComponent().getHeight());
}//GEN-LAST:event_formComponentResized

/*
 * stop the desktop share client as window closing
 */
private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    lcl.stop();
}//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblDisplay;
    // End of variables declaration//GEN-END:variables

    public void setrect(Rectangle r)
    {
        rect=r;
        lblDisplay.setBounds(0, 0, rect.width, rect.height);
        this.setBounds(r);
        System.out.println("setting rect");
    }
    
    /*
     * update screen on the basis of the 
     * new image recieved
     */
    public void UpdateView(Image im)
    {
        System.out.println("updating ");
        
        lblDisplay.getGraphics().drawImage(im, 0, 0, rect.width,rect.height,lblDisplay);
        //lblDisplay.repaint();
    }
}



